"use client"

import { useState, useRef, useEffect } from "react"
import { Mic, X, Sparkles, ArrowUp, FileText } from "lucide-react"
// 將來可能需要導入 LLM 相關庫
// import { generateResponse } from "@/lib/llm-service"

export function ChatbotWidget() {
  const [isOpen, setIsOpen] = useState(false)
  const [showOptions, setShowOptions] = useState(false)
  const [messages, setMessages] = useState([])
  const [inputValue, setInputValue] = useState("")
  const [isListening, setIsListening] = useState(false)
  const [isChatMode, setIsChatMode] = useState(false) // 新增狀態來區分 Ask anything 和 Let's chat 模式
  const messagesEndRef = useRef(null)
  const inputRef = useRef(null)
  const [isProcessing, setIsProcessing] = useState(false)
  const [chatbotBottom, setChatbotBottom] = useState(24) // 24px = bottom-6

  const suggestedQuestions = [
    { text: "What is Qigong?", icon: "💡" },
    { text: "Are there any upcoming events?", icon: "📣" },
    { text: "Join TJM energy family", icon: "🙏" },
  ]

  // 處理發送消息
  const handleSend = () => {
    if (inputValue.trim()) {
      setMessages((prevMessages) => [...prevMessages, { text: inputValue, isUser: true }])
      const currentInput = inputValue
      setInputValue("")

      // 模擬 LLM 處理時間
      setIsProcessing(true)

      // 這裡將來會調用 LLM 服務
      // 目前使用模擬響應
      setTimeout(() => {
        // 這裡將來會替換為實際的 LLM 調用
        // const response = await generateResponse(currentInput)

        // 模擬 LLM 響應
        let response =
          "This is a placeholder response. In the actual implementation, this would be generated by an LLM."

        // 簡單的關鍵詞匹配，僅用於演示
        if (currentInput.toLowerCase().includes("qigong")) {
          response = "This would be an LLM-generated response about Qigong."
        } else if (currentInput.toLowerCase().includes("event")) {
          response = "This would be an LLM-generated response about upcoming events."
        } else if (currentInput.toLowerCase().includes("join") || currentInput.toLowerCase().includes("family")) {
          response = "This would be an LLM-generated response about joining the TJM energy family."
        }

        setMessages((prevMessages) => [...prevMessages, { text: response, isUser: false }])
        setIsProcessing(false)
      }, 1000)
    }
  }

  // 處理按鍵事件
  const handleKeyDown = (e) => {
    if (e.key === "Enter") {
      handleSend()
    }
  }

  // 處理建議問題點擊
  const handleSuggestedQuestion = (question) => {
    setMessages((prevMessages) => [...prevMessages, { text: question, isUser: true }])

    // 模擬 LLM 處理時間
    setIsProcessing(true)

    // 這裡將來會調用 LLM 服務
    setTimeout(() => {
      // 這裡將來會替換為實際的 LLM 調用
      // const response = await generateResponse(question)

      // 模擬 LLM 響應
      let response = "This is a placeholder response. In the actual implementation, this would be generated by an LLM."

      // 簡單的關鍵詞匹配，僅用於演示
      if (question.includes("Qigong")) {
        response = "This would be an LLM-generated response about Qigong."
      } else if (question.includes("upcoming events")) {
        response = "This would be an LLM-generated response about upcoming events."
      } else if (question.includes("Join TJM energy family")) {
        response = "This would be an LLM-generated response about joining the TJM energy family."
      }

      setMessages((prevMessages) => [...prevMessages, { text: response, isUser: false }])
      setIsProcessing(false)
    }, 1000)
  }

  // 模擬語音輸入 -> 改為真實語音輸入
  const handleVoiceInput = () => {
    // 如果已經在聆聽中，則停止
    if (isListening) {
      setIsListening(false)
      if (window.speechRecognition) {
        window.speechRecognition.stop()
      }
      return
    }

    // 檢查瀏覽器支持
    if (!("webkitSpeechRecognition" in window) && !("SpeechRecognition" in window)) {
      alert("您的瀏覽器不支持語音識別功能。請使用 Chrome、Edge 或 Safari 瀏覽器。")
      return
    }

    // 開始聆聽
    setIsListening(true)

    // 創建語音識別實例
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition
    const recognition = new SpeechRecognition()

    // 保存實例以便可以停止
    window.speechRecognition = recognition

    // 配置
    recognition.lang = "en-US" // 設置為英文
    recognition.continuous = false
    recognition.interimResults = false

    // 結果處理
    recognition.onresult = (event) => {
      const transcript = event.results[0][0].transcript

      if (!isChatMode) {
        // Ask anything 模式
        setInputValue(transcript)
      } else {
        // Let's chat 模式 - 直接發送消息
        setMessages((prevMessages) => [...prevMessages, { text: transcript, isUser: true }])

        // 處理回應 (目前是模擬的，將來會替換為 LLM)
        setIsProcessing(true)
        setTimeout(() => {
          const response =
            "This is a placeholder response. In the actual implementation, this would be generated by an LLM."
          setMessages((prevMessages) => [...prevMessages, { text: response, isUser: false }])
          setIsProcessing(false)
        }, 1000)
      }

      setIsListening(false)
    }

    // 錯誤處理
    recognition.onerror = (event) => {
      console.error("Speech recognition error", event.error)
      setIsListening(false)
    }

    // 結束處理
    recognition.onend = () => {
      setIsListening(false)
    }

    // 開始識別
    recognition.start()
  }

  // 打開聊天窗口 - Ask anything 模式
  const openAskChat = () => {
    setIsOpen(true)
    setShowOptions(false)
    setInputValue("")
    setIsChatMode(false)
  }

  // 打開聊天窗口 - Let's chat 模式
  const openVoiceChat = () => {
    setIsOpen(true)
    setShowOptions(false)
    setIsChatMode(true)
  }

  // 關閉聊天窗口
  const closeChat = () => {
    setIsOpen(false)
    setIsListening(false)
  }

  // 自動滾動到最新消息
  useEffect(() => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({ behavior: "smooth" })
    }
  }, [messages])

  // 聊天窗口打開時自動聚焦輸入框
  useEffect(() => {
    if (isOpen && inputRef.current && !isChatMode) {
      inputRef.current.focus()
    }
  }, [isOpen, isChatMode])

  // 4. 添加清理函數，確保在組件卸載時清理定時器
  useEffect(() => {
    return () => {
      // 確保在組件卸載時停止語音輸入
      setIsListening(false)
    }
  }, [])

  // 動態調整 chatbot 位置以與 footer 對齊
  useEffect(() => {
    const handleScroll = () => {
      const windowHeight = window.innerHeight
      const documentHeight = document.documentElement.scrollHeight
      const scrollTop = window.pageYOffset || document.documentElement.scrollTop
      
      // 計算滾動百分比
      const scrollPercentage = scrollTop / (documentHeight - windowHeight)
      
      // 當滾動到底部 20% 時開始調整位置
      if (scrollPercentage > 0.8) {
        // 根據滾動百分比調整 chatbot 位置
        // 當完全滾動到底部時，chatbot 應該距離底部約 80px（與 footer 文字對齊）
        const maxOffset = 80 // 最大偏移量
        const currentOffset = 24 + (maxOffset - 24) * ((scrollPercentage - 0.8) / 0.2)
        setChatbotBottom(Math.min(currentOffset, maxOffset))
      } else {
        // 使用默認位置
        setChatbotBottom(24)
      }
    }

    // 初始計算
    handleScroll()

    // 監聽滾動事件
    window.addEventListener('scroll', handleScroll, { passive: true })
    window.addEventListener('resize', handleScroll, { passive: true })

    return () => {
      window.removeEventListener('scroll', handleScroll)
      window.removeEventListener('resize', handleScroll)
    }
  }, [])

  return (
    <>
      {/* 聊天按鈕 */}
      {!isOpen && (
        <div className="fixed right-3 xs:right-4 md:right-6 flex items-center gap-2 xs:gap-3 z-50" style={{ bottom: `${chatbotBottom}px` }}>
          {showOptions ? (
            <>
              <button
                onClick={openAskChat}
                className="hidden xs:flex items-center gap-2 bg-white rounded-full shadow-lg px-4 xs:px-6 py-2 xs:py-3 animate-fadeIn"
              >
                <div className="flex items-center gap-2 pr-2">
                  <Sparkles size={14} className="xs:size-4 text-gray-700" />
                  <span className="text-xs xs:text-sm font-medium">Ask anything!</span>
                </div>
                <div
                  className="flex items-center gap-1 xs:gap-2 bg-yellow-400 rounded-full px-3 xs:px-4 py-1 xs:py-2 cursor-pointer"
                  onClick={(e) => {
                    e.stopPropagation()
                    openVoiceChat()
                  }}
                >
                  <Mic size={14} className="xs:size-4" />
                  <span className="text-xs xs:text-sm font-medium">Let's chat!</span>
                </div>
              </button>
              <div className="flex-shrink-0 cursor-pointer" onClick={() => setShowOptions(false)}>
                <div className="w-12 h-12 xs:w-14 xs:h-14 md:w-[60px] md:h-[60px] rounded-full shadow-lg hover:scale-110 transition-transform overflow-hidden">
                  <img src="/images/icons/chatbot.png" alt="Chatbot" className="w-full h-full object-cover" />
                </div>
              </div>
            </>
          ) : (
            <div className="cursor-pointer hover:scale-110 transition-transform" onClick={() => setShowOptions(true)}>
              <div className="w-12 h-12 xs:w-14 xs:h-14 md:w-[60px] md:h-[60px] rounded-full shadow-lg overflow-hidden">
                <img src="/images/icons/chatbot.png" alt="Chatbot" className="w-full h-full object-cover" />
              </div>
            </div>
          )}
        </div>
      )}

      {/* 聊天窗口 */}
      {isOpen && (
        <div className="fixed right-3 xs:right-4 md:right-6 flex gap-2 xs:gap-4 z-50" style={{ bottom: `${chatbotBottom}px` }}>
          {/* 聊天窗口 */}
          <div className="w-72 xs:w-80 sm:w-96 bg-white rounded-2xl xs:rounded-3xl shadow-xl flex flex-col max-h-[400px] xs:max-h-[450px] sm:max-h-[500px] relative">
            {/* 聊天內容 */}
            <div className="flex-1 overflow-y-auto p-4 xs:p-6 space-y-3 xs:space-y-4">
              <div className="space-y-3">
                {suggestedQuestions.map((question, index) => (
                  <button
                    key={index}
                    onClick={() => handleSuggestedQuestion(question.text)}
                    className="flex items-center gap-2 bg-yellow-50 hover:bg-yellow-100 text-left px-3 xs:px-4 py-2 rounded-full border border-yellow-200 w-full text-xs xs:text-sm"
                  >
                    <span>{question.icon}</span>
                    <span>{question.text}</span>
                  </button>
                ))}
              </div>

              {/* 顯示聊天歷史 */}
              {messages.length > 0 && (
                <div className="space-y-3 mt-4">
                  {messages.map((message, index) => (
                    <div key={index} className={`flex ${message.isUser ? "justify-end" : "justify-start"}`}>
                                        {!message.isUser && (
                    <div className="mr-2 flex-shrink-0">
                      <div className="w-6 h-6 xs:w-7 xs:h-7 rounded-full overflow-hidden">
                        <img src="/images/icons/chatbot.png" alt="Chatbot" className="w-full h-full object-cover" />
                      </div>
                    </div>
                  )}
                      <div
                        className={`max-w-[80%] rounded-lg px-3 xs:px-4 py-2 text-xs xs:text-sm ${
                          message.isUser ? "bg-yellow-50 border border-yellow-200" : "bg-gray-100"
                        }`}
                      >
                        {message.text}
                      </div>
                    </div>
                  ))}
                </div>
              )}
              {isProcessing && (
                <div className="flex justify-start mt-3">
                  <div className="mr-2 flex-shrink-0">
                    <div className="w-6 h-6 xs:w-7 xs:h-7 rounded-full overflow-hidden">
                      <img src="/images/icons/chatbot.png" alt="Chatbot" className="w-full h-full object-cover" />
                    </div>
                  </div>
                  <div className="bg-gray-100 rounded-lg px-3 xs:px-4 py-2 max-w-[80%]">
                    <div className="flex space-x-2">
                      <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                      <div
                        className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                        style={{ animationDelay: "0.2s" }}
                      ></div>
                      <div
                        className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                        style={{ animationDelay: "0.4s" }}
                      ></div>
                    </div>
                  </div>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>

            {/* 輸入區域 - 根據模式顯示不同的界面 */}
            {!isChatMode ? (
              // Ask anything 模式 - 顯示輸入框
              <div className="p-3 xs:p-4">
                <div className="flex items-center gap-2 bg-gray-100 rounded-full px-3 xs:px-4 py-2 xs:py-3">
                  <input
                    ref={inputRef}
                    type="text"
                    value={inputValue}
                    onChange={(e) => setInputValue(e.target.value)}
                    onKeyDown={handleKeyDown}
                    placeholder="Welcome to TJM energy family!"
                    className="flex-1 bg-transparent outline-none text-xs xs:text-sm placeholder-gray-500"
                    disabled={isListening}
                  />
                  <button
                    onClick={handleVoiceInput}
                    className={`w-7 h-7 xs:w-8 xs:h-8 flex items-center justify-center ${
                      isListening ? "bg-red-500" : "bg-yellow-400"
                    } rounded-full transition-colors`}
                    aria-label="Voice input"
                  >
                    <Mic size={14} className={`xs:size-4 ${isListening ? "animate-pulse" : ""}`} />
                  </button>
                  <button
                    onClick={handleSend}
                    className="w-7 h-7 xs:w-8 xs:h-8 flex items-center justify-center bg-gray-700 rounded-full ml-1"
                    aria-label="Send message"
                  >
                    <ArrowUp size={14} className="xs:size-4 text-white" />
                  </button>
                </div>
              </div>
            ) : (
              // Let's chat 模式 - 顯示語音按鈕
              <div className="p-4 flex justify-center items-center">
                <div className="flex items-center gap-4">
                  <button
                    className="w-10 h-10 flex items-center justify-center bg-gray-200 rounded-full"
                    aria-label="Text mode"
                  >
                    <FileText size={20} className="text-gray-600" />
                  </button>

                  <button
                    onClick={handleVoiceInput}
                    className={`w-16 h-16 flex items-center justify-center ${
                      isListening ? "bg-yellow-400" : "bg-yellow-400"
                    } rounded-full shadow-lg relative`}
                    aria-label={isListening ? "Stop listening" : "Start listening"}
                  >
                    {/* 外圈光暈效果 */}
                    <div
                      className="absolute inset-0 bg-yellow-100 rounded-full -z-10"
                      style={{
                        opacity: 0.7,
                        transform: "scale(1.2)",
                        boxShadow: "0 0 15px 5px rgba(253, 224, 71, 0.3)",
                      }}
                    ></div>

                    {isListening ? (
                      // 聲音感應動畫 - 三條白色線條
                      <div className="flex justify-center items-center space-x-1">
                        <div className="w-1.5 h-4 bg-white rounded-full animate-soundwave1"></div>
                        <div className="w-1.5 h-6 bg-white rounded-full animate-soundwave2"></div>
                        <div className="w-1.5 h-4 bg-white rounded-full animate-soundwave3"></div>
                      </div>
                    ) : (
                      <Mic size={24} className="text-gray-700" />
                    )}
                  </button>

                  <button
                    onClick={closeChat}
                    className="w-10 h-10 flex items-center justify-center bg-gray-200 rounded-full"
                    aria-label="Close chat"
                  >
                    <X size={20} className="text-gray-600" />
                  </button>
                </div>
              </div>
            )}

            {/* 關閉按鈕 - 只在 Ask anything 模式顯示 */}
            {!isChatMode && (
              <button
                onClick={closeChat}
                className="absolute top-2 right-2 text-gray-500 hover:text-gray-700 p-1"
                aria-label="Close chat"
              >
                <X size={20} />
              </button>
            )}
          </div>

          {/* 聊天頭像 - 顯示在右側，點擊可以縮回 */}
          <div
            className="flex-shrink-0 self-start mt-4 cursor-pointer hover:scale-110 transition-transform"
            onClick={closeChat}
            title="點擊縮回聊天窗口"
          >
            <div className="w-[60px] h-[60px] rounded-full shadow-lg overflow-hidden">
              <img src="/images/icons/chatbot.png" alt="Chatbot" className="w-full h-full object-cover" />
            </div>
          </div>
        </div>
      )}
    </>
  )
} 